CREATE TABLE file(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    file_data BYTEA NOT NULL,
    title VARCHAR NOT NULL,
    creation_date timestamp NOT NULL,
    description VARCHAR NOT NULL
)